// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ns_HM_Ashada.Alem.Asar;

#nullable disable

namespace ns_HM_Ashada.Migrations
{
    [DbContext(typeof(Sahife))]
    [Migration("20240913043740_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("ns_HM_Ashada.Alem.Asar.Metn", b =>
                {
                    b.Property<int>("MetnID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ElMetn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MetnID");

                    b.ToTable("Metinler");
                });
#pragma warning restore 612, 618
        }
    }
}
